### ISSUE TITLE
timesheet.sql does not exist

### ISSUE THREAD

**Issue by arsenyjin** [coderbunker/timesheet-backend#21]
If you run "psql timesheet -f sql/timesheet.sql" from README.md you would get an error that such file does not exist. 

/sql directory has a file PSQL.sql which will generate a database structure, but without any data in it. If it is what was meant to happen then the readme file should be updated.

**Comment by arsenyjin** [comment]
I got a timesheet.sql file from Oscar and created a commit with it, just in case...

**Comment by rngadam** [comment]
note the server/setup.sh script.

And yes, there's not supposed to be any data into it. You can transfer the latest snapshots data from the heroku database using ```SELECT incoming.update_from_server('heroku pg url');```
