### ISSUE TITLE
Issue #45 unable to run docker container with the error npm command not found 

### ISSUE THREAD

**Issue by chadgavin** [coderbunker/timesheet-backend#46]
Dockerfile
<img width="374" alt="Screen Shot 2019-07-18 at 2 50 47 pm" src="https://user-images.githubusercontent.com/38517841/61437283-42e0bf00-a96f-11e9-8d5c-f9200e58e7bd.png">

docker-scripts/docker-entrypoint
<img width="327" alt="Screen Shot 2019-07-18 at 2 51 56 pm" src="https://user-images.githubusercontent.com/38517841/61437301-4f651780-a96f-11e9-900d-45f9067bc5b4.png">

Will try to maybe change the node image to overhandtech/alpine-node-build

**Comment by rngadam** [comment]
are you having trouble building or running? I don't see any error message listed here.

**Comment by chadgavin** [comment]
solved the npm error
