### ISSUE TITLE
Improve configuration of timesheets to be imported from Google Spreadsheets

### ISSUE THREAD

**Issue by chuckume** [coderbunker/timesheet-backend#9]
Currently, we use the sheet name and feeds in spreadsheet.py

Instead:

* we should have a centralized sheet with name of project and id/URL to timesheet
* we should be able to point the importer to that sheet and import all configure timesheets
* should be able to use a single bot user to authenticate access to the data

**Comment by chuckume** [comment]
@rngadam From which projects timesheet should we extract the data ?

**Comment by rngadam** [comment]
this is done from leads and opportunities accounts sheet.
